<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Naveen Katepalli, Mrinal Mandapaka, Adiba Khan">
<meta name="dcterms.date" content="2025-08-06">

<title>Clustering Traffic Accidents Using K-Means Clustering</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="index_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clustering Traffic Accidents Using K-Means Clustering</h1>
<p class="subtitle lead">This is a Report</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Naveen Katepalli, Mrinal Mandapaka, Adiba Khan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 6, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>Slides: <a href="slides.html" target="_blank">slides.html</a> ( Go to <code>slides.qmd</code> to edit)</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
</section>
<section id="project-overview" class="level2">
<h2 class="anchored" data-anchor-id="project-overview">Project Overview</h2>
<p>This capstone project applies K-Means Clustering to analyze traffic accident data, aiming to identify high-risk areas (“hotspots”) and uncover contributing factors such as location, time, weather, or road conditions. By grouping similar accidents into clusters, the project provides actionable insights for transportation authorities to implement targeted safety measures, reducing accident frequency and severity (Road accident prediction and model interpretation using a hybrid K-means and random forest algorithm approach, Discover Applied Sciences (2020)).</p>
</section>
<section id="k-means-clustering-for-traffic-accident-analysis" class="level2">
<h2 class="anchored" data-anchor-id="k-means-clustering-for-traffic-accident-analysis">K-Means Clustering for Traffic Accident Analysis</h2>
<p>K-Means Clustering, an unsupervised learning algorithm, segments traffic accident data into K clusters, ensuring incidents within a cluster share similar characteristics while differing from other clusters <span class="citation" data-cites="bao2021kmeans">(<a href="#ref-bao2021kmeans" role="doc-biblioref">Bao 2021</a>)</span>. The process involves:</p>
<ul>
<li><p>Centroid Initialization: Select K initial centroids, ideally using principal component analysis (PCA) to enhance convergence (Efficient Feature Selection with Hybrid K-Means Genetic Algorithm for Text Clustering, Zubair et al., 2022 4th International Conference on Electrical, Computer &amp; Telecommunication Engineering (ICECTE) (2022)).</p></li>
<li><p>Data Assignment: Assign each accident record to the nearest centroid based on Euclidean distance, using features like geographic coordinates, time, or weather (Implementation of K-Means Clustering for Scheduling Courses of Lecturers, Fahlevi et al., IOP Conference Series: Materials Science and Engineering (2020)).</p></li>
<li><p>Centroid Update: Recalculate centroids as the mean of assigned points (Infected Fruit Part Detection Using K-Means Clustering Segmentation Technique, Dubey et al., International Journal of Interactive Multimedia and Artificial Intelligence (2013)).</p></li>
<li><p>Iteration: Repeat until clusters stabilize <span class="citation" data-cites="javadi2017classification">(<a href="#ref-javadi2017classification" role="doc-biblioref">Javadi et al. 2017</a>)</span>. This project uses datasets like New York City’s construction-related accidents or Indian traffic data to cluster incidents by spatial, temporal, or environmental factors, identifying high-risk zones <span class="citation" data-cites="workzone2020">(<a href="#ref-workzone2020" role="doc-biblioref">GitHub 2020</a>)</span>.</p></li>
</ul>
<p>Determining the Optimal Number of Clusters Selecting the optimal K ensures meaningful accident clusters. Methods include:</p>
<ul>
<li><p>Elbow Method: Plots sum of squared errors (SSE) against K, with the “elbow” indicating the optimal number of clusters <span class="citation" data-cites="syakur2018integration">(<a href="#ref-syakur2018integration" role="doc-biblioref">Syakur et al. 2018</a>)</span>.</p></li>
<li><p>Silhouette Method: Evaluates cluster quality using silhouette coefficients (-1 to 1), where 1 indicates well-separated clusters, 0 suggests overlap, and -1 implies misassignment <span class="citation" data-cites="rousseeuw1987silhouettes">(<a href="#ref-rousseeuw1987silhouettes" role="doc-biblioref">Rousseeuw 1987</a>)</span>. Weighted variants improve accuracy <span class="citation" data-cites="lai2024silhouette">(<a href="#ref-lai2024silhouette" role="doc-biblioref">Lai et al. 2024</a>)</span>.</p></li>
<li><p>Gap Statistic: Compares within-cluster dispersion to a reference distribution <span class="citation" data-cites="tibshirani2001estimating">(<a href="#ref-tibshirani2001estimating" role="doc-biblioref">Tibshirani, Walther, and Hastie 2001</a>)</span>. The project employs the Elbow and Silhouette methods to determine K, ensuring robust hotspot identification (K-Means Clustering, Wikipedia (2025); Silhouette (Clustering), Wikipedia (2025)).</p></li>
</ul>
<section id="optimization-and-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="optimization-and-preprocessing">Optimization and Preprocessing</h3>
<p>Large accident datasets benefit from the Canopy algorithm, which partitions data into subsets for efficient clustering <span class="citation" data-cites="yuan2019research">(<a href="#ref-yuan2019research" role="doc-biblioref">Yuan and Yang 2019</a>)</span>. PCA reduces dimensionality, focusing on key features like location or road conditions (Efficient Feature Selection with Hybrid K-Means Genetic Algorithm for Text Clustering, Zubair et al., 2022 4th International Conference on Electrical, Computer &amp; Telecommunication Engineering (ICECTE) (2022)). Silhouette-weighted K-Means enhances cluster quality by prioritizing well-separated incidents <span class="citation" data-cites="lai2024silhouette">(<a href="#ref-lai2024silhouette" role="doc-biblioref">Lai et al. 2024</a>)</span>.</p>
</section>
<section id="cluster-quality-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="cluster-quality-evaluation">Cluster Quality Evaluation</h3>
<p>The Calinski-Harabasz index validates cluster quality, with higher values indicating well-defined accident clusters (The Clustering Quality Based on Calinski-Harabasz Index, Qabbaah, Sammour &amp; Vanhoof, European Journal of Scientific Research (2019)).</p>
</section>
<section id="application-to-traffic-accident-hotspots" class="level3">
<h3 class="anchored" data-anchor-id="application-to-traffic-accident-hotspots">Application to Traffic Accident Hotspots</h3>
<p>The project clusters traffic accident data to identify hotspots and contributing factors. For example, a London study used K-Means with kernel density estimation to group accidents into five categories and 15 clusters based on environmental factors, guiding safety campaigns (Kernel density estimation and K-means clustering to profile road accident hotspots, ScienceDirect (2007)). In India, K-Modes Clustering on 11,574 accidents in Dehradun revealed patterns when combined with association rule mining <span class="citation" data-cites="kumar2015data">(<a href="#ref-kumar2015data" role="doc-biblioref">Kumar and Toshniwal 2015</a>)</span>. Similarly, in Medellín, Colombia, K-Means clustered zones by venue composition to analyze collision trends <span class="citation" data-cites="ocampo2020modelling">(<a href="#ref-ocampo2020modelling" role="doc-biblioref">Ocampo, Alvarez, and Ospina 2020</a>)</span>. This project analyzes datasets like New York City’s 20,000+ construction-related accidents to identify high-risk road segments, potentially due to poor lighting or road geometry, as seen in Iranian studies <span class="citation" data-cites="sadeghi2024identifying">(<a href="#ref-sadeghi2024identifying" role="doc-biblioref">Sadeghi et al. 2024</a>)</span>. Results can guide interventions like improved signage or traffic management.</p>
</section>
</section>
<section id="variations-of-k-means" class="level2">
<h2 class="anchored" data-anchor-id="variations-of-k-means">Variations of K-Means</h2>
<p>Variants enhance K-Means for accident data:</p>
<ul>
<li><p>Constrained K-Means: Ensures meaningful cluster sizes for hotspot analysis <span class="citation" data-cites="usami2014constrained">(<a href="#ref-usami2014constrained" role="doc-biblioref">Usami 2014</a>)</span>.</p></li>
<li><p>Improved K-Means: Reduces computational overhead for large datasets <span class="citation" data-cites="na2010research">(<a href="#ref-na2010research" role="doc-biblioref">Na, Xumin, and Yong 2010</a>)</span>.</p></li>
<li><p>Filtering Algorithm: Uses kd-trees for efficient centroid selection <span class="citation" data-cites="kanungo2002efficient">(<a href="#ref-kanungo2002efficient" role="doc-biblioref">Kanungo et al. 2002</a>)</span>.</p></li>
<li><p>Genetic-Based K-Means (GBKM): Optimizes centroids via genetic algorithms <span class="citation" data-cites="chougule2015genetic">(<a href="#ref-chougule2015genetic" role="doc-biblioref">Chougule et al. 2015</a>)</span>. MapReduce K-Means: Processes large-scale accident data <span class="citation" data-cites="anchalia2013mapreduce">(<a href="#ref-anchalia2013mapreduce" role="doc-biblioref">Anchalia, Koundinya, and Srinath 2013</a>)</span>.</p></li>
<li><p>Silhouette-Weighted K-Means: Improves hotspot detection by weighting incidents <span class="citation" data-cites="semoglou2025silhouette">(<a href="#ref-semoglou2025silhouette" role="doc-biblioref">Semoglou, Likas, and Pavlopoulos 2025</a>)</span>. Limitations</p></li>
</ul>
<p>K-Means struggles with random centroid initialization, which may lead to inconsistent hotspots. Predefining K risks variability, and the algorithm falters with complex, heterogeneous accident data. Careful preprocessing, such as handling missing values and standardizing features, is crucial (The K-Means Algorithm: A Comprehensive Survey and Performance Evaluation, Ahmed, Seraj &amp; Islam, Electronics (2020); K-Means Clustering, Wikipedia (2025)).</p>
<p>K-Means struggles with random centroid initialization, which may lead to inconsistent hotspots. Predefining K risks variability, and the algorithm falters with complex, heterogeneous accident data. Careful preprocessing, such as handling missing values and standardizing features, is crucial <span class="citation" data-cites="ahmed2020kmeans">(<a href="#ref-ahmed2020kmeans" role="doc-biblioref">Ahmed, Seraj, and Islam 2020</a>)</span>.</p>
<section id="project-impact" class="level3">
<h3 class="anchored" data-anchor-id="project-impact">Project Impact</h3>
<p>By identifying accident hotspots and patterns, this project supports transportation authorities in prioritizing interventions, such as enhanced lighting or road redesign, to improve safety (Road accident prediction and model interpretation using a hybrid K-means and random forest algorithm approach, Discover Applied Sciences (2020)). The findings align with studies like those in London and Medellín, offering data-driven solutions to reduce traffic accidents <span class="citation" data-cites="anderson2007kernel">(<a href="#ref-anderson2007kernel" role="doc-biblioref">Anderson 2009</a>)</span>.</p>
</section>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>The approach to K-Means Clustering for this capstone project involves preparing the data, selecting relevant variables, determining the ideal number of clusters, executing the clustering process, and analyzing the resulting groups to identify traffic accident patterns.</p>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<p>Data preparation begins by removing categorical variables (e.g., vehicle type), eliminating outliers (e.g., incorrect coordinates), and applying feature scaling (e.g., normalizing location or time data) to ensure consistency (Raykov et al.&nbsp;2016).</p>
</section>
<section id="variable-selection" class="level3">
<h3 class="anchored" data-anchor-id="variable-selection">Variable Selection</h3>
<p>Key variables are chosen, such as accident coordinates, time, weather, and severity, to highlight factors influencing traffic accident hotspots (A data mining framework to analyze road accident data, Journal of Big Data (2015)).</p>
</section>
<section id="optimal-cluster-determination" class="level3">
<h3 class="anchored" data-anchor-id="optimal-cluster-determination">Optimal Cluster Determination</h3>
<p>The optimal number of clusters is assessed using three techniques:</p>
<ul>
<li><p>Silhouette Coefficient: Evaluates how well each accident fits its cluster compared to others, with scores from -1 to 1 (1 indicating a good fit). It is calculated as (Shi et al.&nbsp;2021): <span class="math display">\[S = \frac{b - a}{\max(a, b)}\]</span> where a is the average intra-cluster distance, and b is the minimum average distance to other clusters.</p></li>
<li><p>Elbow Method: Plots within-cluster sum of squares (WCSS) against cluster numbers, selecting the point where the decrease rate slows. WCSS is defined as (Shi et al.&nbsp;2021): <span class="math display">\[WCSS = \sum_{k=1}^{K} \sum_{x \in C_k} ||x - \mu_k||^2\]</span> where x is a data point, <span class="math inline">\(C_k\)</span> is the cluster, <span class="math inline">\(μ_k\)</span> is the centroid, and K is the total clusters.</p></li>
<li><p>Gap Statistic: Compares within-cluster dispersion to a null reference to find the best K (Tibshirani, Walther &amp; Hastie 2001): <span class="math display">\[Gap_n(k) = E_n^*\{\log(W_k)\} - \log(W_k)\]</span></p></li>
</ul>
<p>where <span class="math inline">\(E_n\)</span> is the expected dispersion, n is sample size, and <span class="math inline">\(W_k\)</span> is within-cluster sum of squares.</p>
</section>
<section id="clustering-process" class="level3">
<h3 class="anchored" data-anchor-id="clustering-process">Clustering Process</h3>
<p>K-Means Clustering is an iterative procedure (Fahlevi et al.&nbsp;2020):</p>
<ul>
<li><p>Set the number of clusters.</p></li>
<li><p>Choose initial centroids randomly.</p></li>
<li><p>Assign data points to the nearest centroid using Euclidean distance: <span class="math display">\[d(x, y) = \sqrt{\sum_{i=1}^n (x_i - y_i)^2}\]</span></p></li>
</ul>
<p>where x and y are points (Ultsch &amp; Lötsch 2022).</p>
<ul>
<li><p>Recalculate centroids as the mean of assigned points.</p></li>
<li><p>Repeat until centroids stabilize.</p></li>
</ul>
</section>
</section>
<section id="analysis-and-results" class="level2">
<h2 class="anchored" data-anchor-id="analysis-and-results">Analysis and Results</h2>
<section id="data-exploration-and-visualization" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration-and-visualization">Data Exploration and Visualization</h3>
<p>A study was conducted to determine how…</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># loading packages </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cluster)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Fatalities.csv"</span>)  <span class="co"># Use your actual CSV file path</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Fatalities_Grouped_By_State <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state, year) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">afatal =</span> <span class="fu">sum</span>(afatal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fatal1517 =</span> <span class="fu">sum</span>(fatal1517, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">fatal1820 =</span> <span class="fu">sum</span>(fatal1820, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Fatalities_Grouped_By_State)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 336 × 5
   state  year afatal fatal1517 fatal1820
   &lt;chr&gt; &lt;int&gt;  &lt;dbl&gt;     &lt;int&gt;     &lt;int&gt;
 1 al     1982   309.        53        99
 2 al     1983   342.        71       108
 3 al     1984   305.        49       103
 4 al     1985   277.        66       100
 5 al     1986   361.        82       120
 6 al     1987   368.        94       127
 7 al     1988   298.        66       105
 8 ar     1982   271.        36        62
 9 ar     1983   248.        35        65
10 ar     1984   183.        34        72
# ℹ 326 more rows</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(Fatalities_Grouped_By_State))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    state                year          afatal         fatal1517     
 Length:336         Min.   :1982   Min.   :  24.6   Min.   :  3.00  
 Class :character   1st Qu.:1983   1st Qu.:  90.5   1st Qu.: 25.75  
 Mode  :character   Median :1985   Median : 211.6   Median : 49.00  
                    Mean   :1985   Mean   : 293.3   Mean   : 62.61  
                    3rd Qu.:1987   3rd Qu.: 364.0   3rd Qu.: 77.00  
                    Max.   :1988   Max.   :2094.9   Max.   :318.00  
   fatal1820    
 Min.   :  7.0  
 1st Qu.: 38.0  
 Median : 82.0  
 Mean   :106.7  
 3rd Qu.:130.2  
 Max.   :601.0  </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(Fatalities_Grouped_By_State)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 336
Columns: 5
$ state     &lt;chr&gt; "al", "al", "al", "al", "al", "al", "al", "ar", "ar", "ar", …
$ year      &lt;int&gt; 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1982, 1983, 1984, …
$ afatal    &lt;dbl&gt; 309.438, 341.834, 304.872, 276.742, 360.716, 368.421, 298.32…
$ fatal1517 &lt;int&gt; 53, 71, 49, 66, 82, 94, 66, 36, 35, 34, 45, 48, 58, 41, 40, …
$ fatal1820 &lt;int&gt; 99, 108, 103, 100, 120, 127, 105, 62, 65, 72, 56, 66, 72, 61…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>hist_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Fatalities_Grouped_By_State, <span class="fu">aes</span>(<span class="at">x =</span> afatal)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Alcohol-Related Fatalities"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Alcohol Fatalities"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hist_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation:</h3>
<ul>
<li><p>Most states have alcohol fatalities clustered in lower ranges (under ~400).</p></li>
<li><p>A few extreme values (e.g., &gt;1000) suggest outliers—likely populous states like California or Texas.</p></li>
<li><p>Distribution is right-skewed, meaning a few states experience disproportionately high fatalities.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>scatter_1517 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Fatalities_Grouped_By_State, <span class="fu">aes</span>(<span class="at">x =</span> afatal, <span class="at">y =</span> fatal1517)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Alcohol Fatalities vs Fatalities Ages 15-17"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Alcohol Fatalities"</span>, <span class="at">y =</span> <span class="st">"Fatalities Ages 15-17"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scatter_1517)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation:</h3>
<ul>
<li><p>A positive trend is visible: states with higher afatal tend to have more teen fatalities.</p></li>
<li><p>However, there is scatter and noise, suggesting other factors also influence teen fatalities (e.g., policy, enforcement).</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>scatter_1820 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Fatalities_Grouped_By_State, <span class="fu">aes</span>(<span class="at">x =</span> afatal, <span class="at">y =</span> fatal1820)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Alcohol Fatalities vs Fatalities Ages 18-20"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Alcohol Fatalities"</span>, <span class="at">y =</span> <span class="st">"Fatalities Ages 18-20"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(scatter_1820)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation:</h3>
<ul>
<li><p>Shows a stronger linear relationship than with ages 15–17.</p></li>
<li><p>Suggests this age group contributes more significantly to overall alcohol fatalities.</p></li>
<li><p>Could point to risky behavior or access to alcohol in college-age populations.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Select numeric columns</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="ot">&lt;-</span> Fatalities_Grouped_By_State <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(afatal, fatal1517, fatal1820)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute correlation matrix</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(numeric_cols, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the correlation matrix</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">method =</span> <span class="st">"number"</span>, <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/correlation-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-3" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-3">Interpretation:</h3>
<ul>
<li><p>afatal vs fatal1820 = 0.8 → strong positive correlation</p></li>
<li><p>afatal vs fatal1517 = 0.6 → moderate correlation</p></li>
<li><p>fatal1517 vs fatal1820 = 0.7 → teens in both groups follow similar trends</p></li>
</ul>
</section>
</section>
<section id="modeling-and-results" class="level2">
<h2 class="anchored" data-anchor-id="modeling-and-results">Modeling and Results</h2>
<p>This section details the data preprocessing, modeling approach, and key findings, weaving a narrative about how the data reveals patterns in traffic accident fatalities across U.S. states from 1982–1988. The story focuses on identifying high-risk areas and understanding the role of alcohol and young drivers in fatal crashes.</p>
<section id="data-preprocessing-and-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-preprocessing-and-cleaning">Data Preprocessing and Cleaning</h3>
<p>To ensure robust clustering, the “Fatalities.csv” dataset was meticulously preprocessed:</p>
<ul>
<li><p>Variable Selection: Focused on afatal (alcohol-related fatalities), fatal1517 (fatalities ages 15–17), and fatal1820 (fatalities ages 18–20) to capture alcohol-related and teen-related accident patterns, critical for identifying high-risk hotspots.</p></li>
<li><p>Missing Data Check: No missing or null values were found, ensuring data integrity.</p></li>
<li><p>Outlier Removal: Outliers were identified using the interquartile range (IQR) method, removing values beyond ( Q1 - 1.5 IQR ) or ( Q3 + 1.5 IQR ) to prevent skewing cluster centroids.</p></li>
<li><p>Feature Scaling: Standardized afatal, fatal1517, and fatal1820 to a mean of 0 and standard deviation of 1, as K-Means clustering relies on Euclidean distance, and unscaled data could bias results.</p></li>
</ul>
<p><strong>Tell a story about what the data reveals.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to detect outliers using the IQR method</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>detect_outliers <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  q1 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  q3 <span class="ot">&lt;-</span> <span class="fu">quantile</span>(x, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  iqr <span class="ot">&lt;-</span> q3 <span class="sc">-</span> q1</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  x <span class="sc">&lt;</span> (q1 <span class="sc">-</span> <span class="fl">1.5</span> <span class="sc">*</span> iqr) <span class="sc">|</span> x <span class="sc">&gt;</span> (q3 <span class="sc">+</span> <span class="fl">1.5</span> <span class="sc">*</span> iqr)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a function to eliminate rows with outliers from specified columns</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>eliminate_outliers <span class="ot">&lt;-</span> <span class="cf">function</span>(df, <span class="at">cols =</span> <span class="fu">names</span>(df)) {</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (col <span class="cf">in</span> cols) {</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    df <span class="ot">&lt;-</span> df[<span class="sc">!</span><span class="fu">detect_outliers</span>(df[[col]]), ]</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(df)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the columns to check for outliers</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>target_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"afatal"</span>, <span class="st">"fatal1517"</span>, <span class="st">"fatal1820"</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove rows with outliers in the target columns</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> <span class="fu">eliminate_outliers</span>(Fatalities_Grouped_By_State, target_columns)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Scale the cleaned data for clustering or further analysis</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>scaled_data <span class="ot">&lt;-</span> <span class="fu">scale</span>(cleaned_data[, target_columns])</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing Scaled Data</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  scaled_data,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Scaled Values"</span>,</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot of Scaled Variables (After Outlier Removal)"</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determining Optimal Number of Clusters: Elbow Method</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)  <span class="co"># For visualizing clustering results</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the Elbow Method using within-cluster sum of squares (WSS)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  scaled_data,             <span class="co"># The scaled data prepared for clustering</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">FUNcluster =</span> kmeans,     <span class="co"># Clustering method: k-means</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"wss"</span>           <span class="co"># WSS: within-cluster sum of squares</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Elbow Method for Determining Optimal Clusters"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Clusters (k)"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Total Within-Cluster Sum of Squares"</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><pre><code>The Elbow Method plot shows the within-cluster sum of squares (WCSS) decreasing as the number of clusters increases, with a noticeable "elbow" at ( K = 3 ).</code></pre></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># K-Means Clustering of Traffic Fatalities</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform K-Means clustering with 3 clusters and 25 random starts</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>kmeans_result <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  scaled_data,      <span class="co"># Scaled data</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">centers =</span> <span class="dv">3</span>,      <span class="co"># Number of clusters</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">nstart =</span> <span class="dv">25</span>       <span class="co"># Number of random initial configurations</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the cluster assignments to the cleaned dataset</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>cleaned_data<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(kmeans_result<span class="sc">$</span>cluster)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizing the Clusters</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the clusters using fviz_cluster</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">object =</span> kmeans_result,          <span class="co"># K-means result object</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> scaled_data,              <span class="co"># Scaled data used for clustering</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">ellipse.type =</span> <span class="st">"convex"</span>,         <span class="co"># Convex hull around clusters</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom =</span> <span class="st">"point"</span>,                  <span class="co"># Points for each observation</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"jco"</span>,                 <span class="co"># Color palette</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggtheme =</span> <span class="fu">theme_minimal</span>()        <span class="co"># Minimal ggplot theme</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"K-Means Clustering of Traffic Fatalities"</span>,</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Principal Component 1"</span>,</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Principal Component 2"</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><pre><code>The visualization shows data points grouped into three clusters with convex ellipses, indicating clear separation and validating the choice of ( K = 3 ).</code></pre></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cluster summary</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>cluster_summary <span class="ot">&lt;-</span> cleaned_data <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">mean</span>(.x, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="cn">NA_character_</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary nicely</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>cluster_summary <span class="sc">%&gt;%</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Table: Average Values of Numeric Variables by Cluster"</span>, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">"center"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table: Average Values of Numeric Variables by Cluster</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">cluster</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">afatal</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fatal1517</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">fatal1820</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">state</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">1985.04</td>
<td style="text-align: right;">81.76</td>
<td style="text-align: right;">19.02</td>
<td style="text-align: right;">31.54</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">1985.13</td>
<td style="text-align: right;">475.01</td>
<td style="text-align: right;">108.47</td>
<td style="text-align: right;">175.07</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">1984.92</td>
<td style="text-align: right;">255.68</td>
<td style="text-align: right;">56.31</td>
<td style="text-align: right;">93.80</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><p>The bar plot visually confirms that Cluster 2 has significantly higher alcohol-related fatalities (475) compared to Cluster 3 (256) and Cluster 1 (81.8).</p></li>
<li><p>This stark contrast underscores Cluster 2 as the primary target for alcohol-related interventions, as its fatalities are nearly six times higher than Cluster 1’s, highlighting the urgency of addressing urban hotspots.</p></li>
<li><p>The distinct heights of the bars reinforce the clustering results, showing clear differentiation in risk levels across the three groups.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------------------------</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar Plot: Alcohol-Related Fatalities by Cluster</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------------------------</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required library</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bar plot for average alcohol-related fatalities per cluster</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cluster_summary, <span class="fu">aes</span>(<span class="at">x =</span> cluster, <span class="at">y =</span> afatal, <span class="at">fill =</span> cluster)) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">stat =</span> <span class="st">"identity"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">show.legend =</span> <span class="cn">FALSE</span>  <span class="co"># Hides redundant legend since color = cluster</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Alcohol-Related Fatalities by Cluster"</span>,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Cluster"</span>,</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average Alcohol-Related Fatalities"</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The bar plot visually confirms that Cluster 2 has significantly higher alcohol-related fatalities (475) compared to Cluster 3 (256) and Cluster 1 (81.8).</p></li>
<li><p>This stark contrast underscores Cluster 2 as the primary target for alcohol-related interventions, as its fatalities are nearly six times higher than Cluster 1’s, highlighting the urgency of addressing urban hotspots.</p></li>
<li><p>The distinct heights of the bars reinforce the clustering results, showing clear differentiation in risk levels across the three groups.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Principal Component Analysis (PCA)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform PCA on the scaled data</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>pca_result <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  scaled_data,      <span class="co"># Data already scaled for clustering</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">center =</span> <span class="cn">TRUE</span>,    <span class="co"># Center the variables</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">scale. =</span> <span class="cn">TRUE</span>     <span class="co"># Scale the variables to unit variance</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Scree Plot: Variance Explained by Principal Components</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the proportion of variance explained by each principal component</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(pca_result) <span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scree Plot of PCA Variance Explained"</span>,</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Principal Components"</span>,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Percentage of Variance Explained"</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The scree plot shows the proportion of variance explained by each principal component, with the first two components accounting for approximately 80% of the total variance.</p></li>
<li><p>This indicates that afatal, fatal1517, and fatal1820 are effectively summarized by two dimensions, suggesting that alcohol-related and teen fatalities are the primary drivers of differences across states.</p></li>
<li><p>The sharp drop after the second component confirms that additional components add little explanatory power, validating the use of PCA for dimensionality reduction.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PCA Variable Correlation Circle</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize how original variables contribute to the principal components</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  pca_result,                       <span class="co"># PCA result object</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.var =</span> <span class="st">"contrib"</span>,             <span class="co"># Color by contribution to PCs</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>),  <span class="co"># Gradient for contribution</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">repel =</span> <span class="cn">TRUE</span>                     <span class="co"># Avoid label overlap</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"PCA Variable Correlation Circle"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Principal Component 1"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Principal Component 2"</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The correlation circle illustrates the relationships between afatal, fatal1517, and fatal1820 in the PCA space.</p></li>
<li><p>afatal and fatal1820 are closely aligned with the first principal component (PC1), indicating they contribute significantly to the primary source of variance, likely due to their strong correlation (0.8).</p></li>
<li><p>fatal1517 contributes to both PC1 and PC2, suggesting it plays a secondary but notable role in differentiating states, consistent with its moderate correlation with afatal (0.6).</p></li>
<li><p>The distinct positioning of variables confirms their unique contributions to the data’s structure, supporting the clustering results.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PCA Projection of Observations by Cluster</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize observations in the PCA space, colored by cluster</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  pca_result,                   <span class="co"># PCA result object</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">geom.ind =</span> <span class="st">"point"</span>,           <span class="co"># Use points to represent observations</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.ind =</span> cleaned_data<span class="sc">$</span>cluster,  <span class="co"># Color points by cluster assignment</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">palette =</span> <span class="st">"jco"</span>,              <span class="co"># Use a clean and readable color palette</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">addEllipses =</span> <span class="cn">TRUE</span>,           <span class="co"># Draw ellipses around clusters</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.title =</span> <span class="st">"Cluster"</span>      <span class="co"># Title for legend</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"PCA Projection of Observations by Cluster"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Principal Component 1"</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Principal Component 2"</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The PCA projection plot shows individual state-year observations projected onto the first two principal components, colored by cluster with ellipses indicating cluster boundaries.</p></li>
<li><p>Clear separation between clusters validates the K-Means results: Cluster 2 (high-risk) is distinctly separated from Cluster 1 (low-risk), with Cluster 3 (moderate-risk) occupying an intermediate position.</p></li>
<li><p>This separation confirms that the clusters capture meaningful differences in fatality patterns, with Cluster 2’s position reflecting its high afatal and fatal1820 values, reinforcing the urban hotspot narrative.</p></li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------------------------</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Geographic Distribution of Clusters</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------------------------------------------------------</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a lookup table to map state abbreviations to full state names (lowercase)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>state_lookup <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">abbr =</span> <span class="fu">tolower</span>(state.abb),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">full =</span> <span class="fu">tolower</span>(state.name)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add special handling for Washington, D.C., which isn't included in base R state vectors</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>state_lookup <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  state_lookup,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">abbr =</span> <span class="st">"dc"</span>, <span class="at">full =</span> <span class="st">"district of columbia"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert state abbreviations in the dataset to full state names</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>cleaned_data<span class="sc">$</span>state <span class="ot">&lt;-</span> state_lookup<span class="sc">$</span>full[<span class="fu">match</span>(<span class="fu">tolower</span>(cleaned_data<span class="sc">$</span>state), state_lookup<span class="sc">$</span>abbr)]</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare Data for Mapping -  Get U.S. map data from ggplot2</span></span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>us_map <span class="ot">&lt;-</span> <span class="fu">map_data</span>(<span class="st">"state"</span>)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign cluster values to map data based on matching state names</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>us_map<span class="sc">$</span>cluster <span class="ot">&lt;-</span> cleaned_data<span class="sc">$</span>cluster[<span class="fu">match</span>(us_map<span class="sc">$</span>region, cleaned_data<span class="sc">$</span>state)]</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>us_map<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(us_map<span class="sc">$</span>cluster)</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the U.S. Map Colored by Cluster</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(maps)</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the map with states filled by cluster color</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(us_map, <span class="fu">aes</span>(<span class="at">x =</span> long, <span class="at">y =</span> lat, <span class="at">group =</span> group, <span class="at">fill =</span> cluster)) <span class="sc">+</span></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_polygon</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span>  <span class="co"># Clean, borderless map</span></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"blue"</span>),</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">na.value =</span> <span class="st">"white"</span>  <span class="co"># States with no cluster info shown in white</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Geographic Distribution of Clusters"</span>,</span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Cluster"</span></span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The geographic map visualizes clusters across U.S. states, with each state colored by its cluster assignment (red for Cluster 1, green for Cluster 2, blue for Cluster 3).</p></li>
<li><p>Cluster 1 (Low-Risk): Predominantly in rural Midwest and Great Plains states (e.g., Nebraska, Iowa), where low population density and traffic volume contribute to fewer fatalities.</p></li>
</ul>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This project utilized K-Means clustering and Principal Component Analysis (PCA) on the “Fatalities.csv” dataset from the U.S. Department of Transportation’s Fatal Accident Reporting System (1982–1988) to identify patterns in traffic accident fatalities across U.S. states. The analysis revealed three distinct clusters based on alcohol-related fatalities (afatal), fatalities for ages 15–17 (fatal1517), and ages 18–20 (fatal1820):</p>
<ul>
<li>Cluster 1 (Low-Risk, 112 states): Characterized by low fatalities (81.8 alcohol-related, 19.0 ages 15–17, 31.5 ages 18–20), primarily in rural states like Nebraska and Iowa, where lower traffic density and fewer alcohol-related incidents contribute to safer roads.</li>
<li>Cluster 2 (High-Risk, 89 states): Marked by high fatalities (475 alcohol-related, 108 ages 15–17, 175 ages 18–20), concentrated in urban states such as California and Texas, indicating hotspots driven by high traffic volumes and alcohol accessibility.</li>
<li>Cluster 3 (Moderate-Risk, 74 states): Exhibited moderate fatalities (256 alcohol-related, 56.3 ages 15–17, 93.8 ages 18–20), representing states with mixed urban-rural characteristics, primarily in the South and West.</li>
</ul>
<p>PCA analysis showed that the first two principal components explained approximately 80% of the variance, with afatal and fatal1820 as the primary drivers, underscoring the significant role of alcohol and young drivers (ages 18–20) in fatality patterns. Geographic visualization highlighted an urban-rural divide, with high-risk clusters in urbanized states and low-risk clusters in rural areas. The clustering achieved a between_SS/total_SS of 65.2%, indicating a reasonable fit, validated by clear separation in PCA projections and geographic mappings.</p>
<p>The findings reveal a critical narrative of risk disparities across U.S. states, with urban areas (Cluster 2) facing a disproportionate burden of alcohol-related and teen fatalities, particularly among 18–20-year-olds. These insights have significant implications for transportation safety policies:</p>
<ul>
<li>Targeted Enforcement: Urban states like California and Texas require stricter DUI patrols and penalties to address the high incidence of alcohol-related fatalities (475 on average in Cluster 2). Enhanced enforcement could reduce risky behaviors, particularly among young drivers.</li>
<li>Education Campaigns: Public awareness programs targeting 18–20-year-olds, especially in urban settings, are essential to curb drinking and driving. College campuses, where this age group is prevalent, could host alcohol education initiatives to promote safer behaviors.</li>
<li>Infrastructure Improvements: High-risk urban zones need infrastructure enhancements, such as improved lighting, road signage, or traffic calming measures, to mitigate crash severity, especially in areas with high traffic volumes.</li>
</ul>
<p>The urban-rural divide suggests that resource allocation should prioritize urban hotspots while maintaining lighter interventions in low-risk rural states (Cluster 1). The moderate-risk Cluster 3 indicates a need for balanced strategies in mixed regions. However, the dataset’s age (1982–1988) limits its applicability to modern contexts, as traffic patterns, vehicle safety, and alcohol regulations have evolved.</p>
<p>Additionally, K-Means clustering’s sensitivity to centroid initialization necessitates robust validation methods, such as the Elbow and Silhouette approaches used here. Future analyses could incorporate recent data or additional variables (e.g., road conditions, weather, or vehicle types) to enhance hotspot identification, drawing inspiration from successful studies in London and Medellín (ScienceDirect, 2007, 2020). These findings provide a data-driven foundation for policymakers to reduce traffic fatalities, particularly in high-risk urban areas, ultimately saving lives through targeted, evidence-based interventions.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ahmed2020kmeans" class="csl-entry" role="listitem">
Ahmed, M., R. Seraj, and S. M. S. Islam. 2020. <span>“The k-Means Algorithm: A Comprehensive Survey and Performance Evaluation.”</span> <em>Electronics</em> 9 (8): 1295.
</div>
<div id="ref-anchalia2013mapreduce" class="csl-entry" role="listitem">
Anchalia, P. P., A. K. Koundinya, and N. K. Srinath. 2013. <span>“MapReduce Design of k-Means Clustering Algorithm.”</span> In <em>2013 International Conference on Information Science and Applications (ICISA)</em>, 1–5. IEEE.
</div>
<div id="ref-anderson2007kernel" class="csl-entry" role="listitem">
Anderson, T. K. 2009. <span>“Kernel Density Estimation and k-Means Clustering to Profile Road Accident Hotspots.”</span> <em>Accident Analysis &amp; Prevention</em> 41 (3): 359–64.
</div>
<div id="ref-bao2021kmeans" class="csl-entry" role="listitem">
Bao, C. 2021. <span>“K-Means Clustering Algorithm: A Brief Review.”</span> <em>Francis Academic Press</em>.
</div>
<div id="ref-chougule2015genetic" class="csl-entry" role="listitem">
Chougule, P., A. D. Thakare, P. Kale, M. Gole, and P. Nanekar. 2015. <span>“Genetic k-Means Clustering Algorithm for Documents.”</span> <em>International Journal of Computer Applications</em> 6 (2): 1724–27.
</div>
<div id="ref-workzone2020" class="csl-entry" role="listitem">
GitHub. 2020. <span>“Workzone-Collision-Analysis/Capstone.”</span> <a href="https://github.com/workzone-collision-analysis/capstone" class="uri">https://github.com/workzone-collision-analysis/capstone</a>.
</div>
<div id="ref-javadi2017classification" class="csl-entry" role="listitem">
Javadi, S., S. M. Hashemy, K. Mohammadi, K. W. F. Howard, and A. Neshat. 2017. <span>“Classification of Aquifer Vulnerability Using k-Means Cluster Analysis.”</span> <em>Journal of Hydrology</em> 549: 27–37.
</div>
<div id="ref-kanungo2002efficient" class="csl-entry" role="listitem">
Kanungo, T., D. M. Mount, N. S. Netanyahu, C. D. Piatko, R. Silverman, and A. Y. Wu. 2002. <span>“An Efficient k-Means Clustering Algorithm: Analysis and Implementation.”</span> <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em> 24 (7): 881–92.
</div>
<div id="ref-kumar2015data" class="csl-entry" role="listitem">
Kumar, S., and D. Toshniwal. 2015. <span>“A Data Mining Framework to Analyze Road Accident Data.”</span> <em>Journal of Big Data</em> 2 (1): 1–22.
</div>
<div id="ref-lai2024silhouette" class="csl-entry" role="listitem">
Lai, D., Y. Zhang, X. Zhang, Y. Su, and M. A. Bin. 2024. <span>“Silhouette-Coefficient Based Weighting k-Means.”</span> <em>Neural Computing and Applications</em>.
</div>
<div id="ref-na2010research" class="csl-entry" role="listitem">
Na, S., L. Xumin, and G. Yong. 2010. <span>“Research on k-Means Clustering Algorithm: An Improved k-Means Clustering Algorithm.”</span> In <em>2010 Third International Symposium on Intelligent Information Technology and Security Informatics</em>, 63–67. IEEE.
</div>
<div id="ref-ocampo2020modelling" class="csl-entry" role="listitem">
Ocampo, L., P. Alvarez, and J. Ospina. 2020. <span>“Modelling Road Traffic Collisions Using Clustered Zones Based on Foursquare Data in Medellín.”</span> <em>Transportation Research Interdisciplinary Perspectives</em> 7: 100203.
</div>
<div id="ref-rousseeuw1987silhouettes" class="csl-entry" role="listitem">
Rousseeuw, P. J. 1987. <span>“Silhouettes: A Graphical Aid to the Interpretation and Validation of Cluster Analysis.”</span> <em>Journal of Computational and Applied Mathematics</em> 20: 53–65.
</div>
<div id="ref-sadeghi2024identifying" class="csl-entry" role="listitem">
Sadeghi, A., H. Farhad, A. Mohammadzadeh Moghaddam, and M. Jalili Qazizadeh. 2024. <span>“Identifying Accident Prone Areas and Factors Influencing the Severity of Crashes Using Machine Learning and Spatial Analyses.”</span> <em>Scientific Reports</em> 14 (1): 15736.
</div>
<div id="ref-semoglou2025silhouette" class="csl-entry" role="listitem">
Semoglou, A., A. Likas, and G. A. Pavlopoulos. 2025. <span>“Silhouette-Guided Instance-Weighted k-Means (k-Sil).”</span> <em>arXiv</em>.
</div>
<div id="ref-syakur2018integration" class="csl-entry" role="listitem">
Syakur, M. A., B. K. Khotimah, E. M. S. Rochman, and B. D. Satoto. 2018. <span>“Integration k-Means Clustering Method and Elbow Method for Identification of the Best Customer Profile Cluster.”</span> In <em>IOP Conference Series: Materials Science and Engineering</em>, 336:012017.
</div>
<div id="ref-tibshirani2001estimating" class="csl-entry" role="listitem">
Tibshirani, R., G. Walther, and T. Hastie. 2001. <span>“Estimating the Number of Clusters in a Data Set via the Gap Statistic.”</span> <em>Journal of the Royal Statistical Society: Series B (Statistical Methodology)</em> 63 (2): 411–23.
</div>
<div id="ref-usami2014constrained" class="csl-entry" role="listitem">
Usami, S. 2014. <span>“Constrained k-Means Clustering and Its Application to Pattern Recognition.”</span> <em>The Japanese Journal of Behaviormetrics</em> 41 (1): 25–34.
</div>
<div id="ref-yuan2019research" class="csl-entry" role="listitem">
Yuan, C., and H. Yang. 2019. <span>“Research on k-Value Selection Method of k-Means Clustering Algorithm.”</span> <em>Journal of Multidisciplinary Scientific Journal</em> 2 (2): 226–35.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>